const Data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirt',
      image: '/images/photo-1542291026-7eec264c27ff.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 1,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-two',
      id: 32845798,
      category: 'shirt',
      image: '/images/photo-1560343090-f0409e92791a.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 2,
      numReviews: 8,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-three',
      category: 'shirt',
      image: '/images/photo-1491553895911-0055eca6402d.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 3,
      numReviews: 7,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-four',
      category: 'shirt',
      image: '/images/photo-1503602642458-232111445657.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 6,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-five',
      category: 'shirt',
      image: '/images/photo-1505740420928-5e560c06d30e.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 2,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-six',
      category: 'shirt',
      image: '/images/photo-1523275335684-37898b6baf30.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 1,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-seven',
      category: 'shirt',
      image: '/images/photo-1526170375885-4d8ecf77b99f.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 9,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-eight',
      category: 'shirt',
      image: '/images/photo-1572635196237-14b3f281503f.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-nine',
      category: 'shirt',
      image: '/images/photo-1586495777744-4413f21062fa.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt-ten',
      category: 'shirt',
      image: '/images/photo-1638913662584-731da41f5a59.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};
export default Data;
